spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
      hibernate:
          ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          # use_sql_comments: true
          format_sql: true
  logging:
    level:
      org:
        hibernate:
          # To log values:
          type: TRACE